### ISSUE TITLE
type=file is not a name or some shit

### ISSUE THREAD

**Issue by icantrank** [jsphpl/redirect-mapper#1]
Yo dude, I'm using your thing, it's awesome cheers.

I had to make a change on line 90 and 92 for it to run in latest python 3.something and newset versions of dependancies:

type=file doesn't work, replacing it with type=argparse.FileType('r') fixes the issue.

I'm not a python coder but reading the docs for argparser there is no file type, but it supports custom def'd types, so maybe you forgot that idk.

MAybe something to take a look at dude, but nice one, cheers, I'm using it now and it's working sweet.

**Comment by jsphpl** [comment]
Thanks for the feedback! Could reproduce the issue under Python 3 and deployed a fix…
